// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RespStream.proto

package com.imooc.tenlesson;

public interface MyResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tenlesson.MyResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
   */
  java.util.List<MyResponseStream>
      getRespStreamList();
  /**
   * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
   */
  MyResponseStream getRespStream(int index);
  /**
   * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
   */
  int getRespStreamCount();
  /**
   * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
   */
  java.util.List<? extends MyResponseStreamOrBuilder>
      getRespStreamOrBuilderList();
  /**
   * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
   */
  MyResponseStreamOrBuilder getRespStreamOrBuilder(
          int index);
}
