// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RespStream.proto

package com.imooc.tenlesson;

/**
 * Protobuf type {@code tenlesson.MyResponseList}
 */
public  final class MyResponseList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tenlesson.MyResponseList)
    MyResponseListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MyResponseList.newBuilder() to construct.
  private MyResponseList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MyResponseList() {
    respStream_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new MyResponseList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MyResponseList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              respStream_ = new java.util.ArrayList<MyResponseStream>();
              mutable_bitField0_ |= 0x00000001;
            }
            respStream_.add(
                input.readMessage(MyResponseStream.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        respStream_ = java.util.Collections.unmodifiableList(respStream_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RespStream.internal_static_tenlesson_MyResponseList_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RespStream.internal_static_tenlesson_MyResponseList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MyResponseList.class, Builder.class);
  }

  public static final int RESPSTREAM_FIELD_NUMBER = 1;
  private java.util.List<MyResponseStream> respStream_;
  /**
   * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
   */
  public java.util.List<MyResponseStream> getRespStreamList() {
    return respStream_;
  }
  /**
   * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
   */
  public java.util.List<? extends MyResponseStreamOrBuilder>
      getRespStreamOrBuilderList() {
    return respStream_;
  }
  /**
   * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
   */
  public int getRespStreamCount() {
    return respStream_.size();
  }
  /**
   * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
   */
  public MyResponseStream getRespStream(int index) {
    return respStream_.get(index);
  }
  /**
   * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
   */
  public MyResponseStreamOrBuilder getRespStreamOrBuilder(
      int index) {
    return respStream_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < respStream_.size(); i++) {
      output.writeMessage(1, respStream_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < respStream_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, respStream_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MyResponseList)) {
      return super.equals(obj);
    }
    MyResponseList other = (MyResponseList) obj;

    if (!getRespStreamList()
        .equals(other.getRespStreamList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRespStreamCount() > 0) {
      hash = (37 * hash) + RESPSTREAM_FIELD_NUMBER;
      hash = (53 * hash) + getRespStreamList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MyResponseList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MyResponseList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MyResponseList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MyResponseList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MyResponseList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MyResponseList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MyResponseList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MyResponseList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MyResponseList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MyResponseList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MyResponseList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MyResponseList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MyResponseList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tenlesson.MyResponseList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tenlesson.MyResponseList)
      com.imooc.tenlesson.MyResponseListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RespStream.internal_static_tenlesson_MyResponseList_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RespStream.internal_static_tenlesson_MyResponseList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MyResponseList.class, Builder.class);
    }

    // Construct using com.imooc.tenlesson.MyResponseList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRespStreamFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (respStreamBuilder_ == null) {
        respStream_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        respStreamBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RespStream.internal_static_tenlesson_MyResponseList_descriptor;
    }

    @Override
    public MyResponseList getDefaultInstanceForType() {
      return MyResponseList.getDefaultInstance();
    }

    @Override
    public MyResponseList build() {
      MyResponseList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public MyResponseList buildPartial() {
      MyResponseList result = new MyResponseList(this);
      int from_bitField0_ = bitField0_;
      if (respStreamBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          respStream_ = java.util.Collections.unmodifiableList(respStream_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.respStream_ = respStream_;
      } else {
        result.respStream_ = respStreamBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MyResponseList) {
        return mergeFrom((MyResponseList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MyResponseList other) {
      if (other == MyResponseList.getDefaultInstance()) return this;
      if (respStreamBuilder_ == null) {
        if (!other.respStream_.isEmpty()) {
          if (respStream_.isEmpty()) {
            respStream_ = other.respStream_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRespStreamIsMutable();
            respStream_.addAll(other.respStream_);
          }
          onChanged();
        }
      } else {
        if (!other.respStream_.isEmpty()) {
          if (respStreamBuilder_.isEmpty()) {
            respStreamBuilder_.dispose();
            respStreamBuilder_ = null;
            respStream_ = other.respStream_;
            bitField0_ = (bitField0_ & ~0x00000001);
            respStreamBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRespStreamFieldBuilder() : null;
          } else {
            respStreamBuilder_.addAllMessages(other.respStream_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MyResponseList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MyResponseList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<MyResponseStream> respStream_ =
      java.util.Collections.emptyList();
    private void ensureRespStreamIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        respStream_ = new java.util.ArrayList<MyResponseStream>(respStream_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        MyResponseStream, MyResponseStream.Builder, MyResponseStreamOrBuilder> respStreamBuilder_;

    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public java.util.List<MyResponseStream> getRespStreamList() {
      if (respStreamBuilder_ == null) {
        return java.util.Collections.unmodifiableList(respStream_);
      } else {
        return respStreamBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public int getRespStreamCount() {
      if (respStreamBuilder_ == null) {
        return respStream_.size();
      } else {
        return respStreamBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public MyResponseStream getRespStream(int index) {
      if (respStreamBuilder_ == null) {
        return respStream_.get(index);
      } else {
        return respStreamBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public Builder setRespStream(
        int index, MyResponseStream value) {
      if (respStreamBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRespStreamIsMutable();
        respStream_.set(index, value);
        onChanged();
      } else {
        respStreamBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public Builder setRespStream(
        int index, MyResponseStream.Builder builderForValue) {
      if (respStreamBuilder_ == null) {
        ensureRespStreamIsMutable();
        respStream_.set(index, builderForValue.build());
        onChanged();
      } else {
        respStreamBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public Builder addRespStream(MyResponseStream value) {
      if (respStreamBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRespStreamIsMutable();
        respStream_.add(value);
        onChanged();
      } else {
        respStreamBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public Builder addRespStream(
        int index, MyResponseStream value) {
      if (respStreamBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRespStreamIsMutable();
        respStream_.add(index, value);
        onChanged();
      } else {
        respStreamBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public Builder addRespStream(
        MyResponseStream.Builder builderForValue) {
      if (respStreamBuilder_ == null) {
        ensureRespStreamIsMutable();
        respStream_.add(builderForValue.build());
        onChanged();
      } else {
        respStreamBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public Builder addRespStream(
        int index, MyResponseStream.Builder builderForValue) {
      if (respStreamBuilder_ == null) {
        ensureRespStreamIsMutable();
        respStream_.add(index, builderForValue.build());
        onChanged();
      } else {
        respStreamBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public Builder addAllRespStream(
        Iterable<? extends MyResponseStream> values) {
      if (respStreamBuilder_ == null) {
        ensureRespStreamIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, respStream_);
        onChanged();
      } else {
        respStreamBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public Builder clearRespStream() {
      if (respStreamBuilder_ == null) {
        respStream_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        respStreamBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public Builder removeRespStream(int index) {
      if (respStreamBuilder_ == null) {
        ensureRespStreamIsMutable();
        respStream_.remove(index);
        onChanged();
      } else {
        respStreamBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public MyResponseStream.Builder getRespStreamBuilder(
        int index) {
      return getRespStreamFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public MyResponseStreamOrBuilder getRespStreamOrBuilder(
        int index) {
      if (respStreamBuilder_ == null) {
        return respStream_.get(index);  } else {
        return respStreamBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public java.util.List<? extends MyResponseStreamOrBuilder>
         getRespStreamOrBuilderList() {
      if (respStreamBuilder_ != null) {
        return respStreamBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(respStream_);
      }
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public MyResponseStream.Builder addRespStreamBuilder() {
      return getRespStreamFieldBuilder().addBuilder(
          MyResponseStream.getDefaultInstance());
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public MyResponseStream.Builder addRespStreamBuilder(
        int index) {
      return getRespStreamFieldBuilder().addBuilder(
          index, MyResponseStream.getDefaultInstance());
    }
    /**
     * <code>repeated .tenlesson.MyResponseStream respStream = 1;</code>
     */
    public java.util.List<MyResponseStream.Builder>
         getRespStreamBuilderList() {
      return getRespStreamFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        MyResponseStream, MyResponseStream.Builder, MyResponseStreamOrBuilder>
        getRespStreamFieldBuilder() {
      if (respStreamBuilder_ == null) {
        respStreamBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            MyResponseStream, MyResponseStream.Builder, MyResponseStreamOrBuilder>(
                respStream_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        respStream_ = null;
      }
      return respStreamBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tenlesson.MyResponseList)
  }

  // @@protoc_insertion_point(class_scope:tenlesson.MyResponseList)
  private static final MyResponseList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MyResponseList();
  }

  public static MyResponseList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MyResponseList>
      PARSER = new com.google.protobuf.AbstractParser<MyResponseList>() {
    @Override
    public MyResponseList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MyResponseList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MyResponseList> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MyResponseList> getParserForType() {
    return PARSER;
  }

  @Override
  public MyResponseList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

