// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RespStream.proto

package com.imooc.tenlesson;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tenlesson.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
