// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RespStream.proto

package com.imooc.tenlesson;

public final class RespStream {
  private RespStream() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tenlesson_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tenlesson_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tenlesson_MyResponseStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tenlesson_MyResponseStream_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tenlesson_MyResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tenlesson_MyResponseList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020RespStream.proto\022\ttenlesson\"\030\n\tMyReque" +
      "st\022\013\n\003age\030\001 \001(\005\";\n\020MyResponseStream\022\014\n\004n" +
      "ame\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"A\n\016" +
      "MyResponseList\022/\n\nrespStream\030\001 \003(\0132\033.ten" +
      "lesson.MyResponseStream2\240\001\n\rPersonServic" +
      "e\022G\n\016getPersonByAge\022\024.tenlesson.MyReques" +
      "t\032\033.tenlesson.MyResponseStream\"\0000\001\022F\n\017ge" +
      "tPersonByAges\022\024.tenlesson.MyRequest\032\031.te" +
      "nlesson.MyResponseList\"\000(\001B#\n\023com.imooc." +
      "tenlessonB\nRespStreamP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tenlesson_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tenlesson_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tenlesson_MyRequest_descriptor,
        new String[] { "Age", });
    internal_static_tenlesson_MyResponseStream_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tenlesson_MyResponseStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tenlesson_MyResponseStream_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_tenlesson_MyResponseList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tenlesson_MyResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tenlesson_MyResponseList_descriptor,
        new String[] { "RespStream", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
