// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.imooc.ninelesson;

public final class GrpcData {
  private GrpcData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ninelesson_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ninelesson_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ninelesson_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ninelesson_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014Person.proto\022\nninelesson\"\031\n\tMyRequest\022" +
      "\014\n\004name\030\001 \001(\t\"\036\n\nMyResponse\022\020\n\010fullName\030" +
      "\002 \001(\t2M\n\013NameService\022>\n\013getFullName\022\025.ni" +
      "nelesson.MyRequest\032\026.ninelesson.MyRespon" +
      "se\"\000B\"\n\024com.imooc.ninelessonB\010GrpcDataP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ninelesson_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ninelesson_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ninelesson_MyRequest_descriptor,
        new String[] { "Name", });
    internal_static_ninelesson_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ninelesson_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ninelesson_MyResponse_descriptor,
        new String[] { "FullName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
