// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.imooc.ninelesson;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ninelesson.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fullName = 2;</code>
   */
  String getFullName();
  /**
   * <code>string fullName = 2;</code>
   */
  com.google.protobuf.ByteString
      getFullNameBytes();
}
