// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.imooc.ninelesson;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ninelesson.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
